import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
// @ - is a shortcut provided by the Next js restart our route with src/
import Unnecessary from "@/components/Unncessary";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Unnecessary />
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
